config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :hotels, only: [:new, :create] do
    resources :bookings, only: [:new, :create]
  end

  mount Bookings::API => '/api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :bookings

  def self.ensure google_id:
    hotel = find_by_google_id(google_id)
    return hotel if hotel

    google_place = find_google_place google_id
    return unless google_place

    create(
      city: google_place.city,
      name: google_place.name,
      google_id: google_place.place_id
    )
  end

  def self.find_google_place(google_id)
    GooglePlaces::Spot.find(google_id, ENV['GOOGLE_PLACES_API_KEY'])
  rescue GooglePlaces::InvalidRequestError => e
    logger.error "Can't find google place with id=#{google_id}"
    return nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_filter :ensure_hotel

  def new
    @booking_form = BookingForm.new(hotel_id: @hotel.id)
  end

  def create
    result = MakeBooking.call(booking_params: booking_params, hotel: @hotel)
    if result.success?
      redirect_to root_url
    else
      @booking_form = result.form
      @errors = result.errors
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking_form).permit(
      :started_at,
      :ended_at,
      :user_name,
      :user_email,
      :hotel_id
    )
  end

  def ensure_hotel
    result = EnsureHotel.call(google_id: params[:hotel_id])
    if result.success?
      @hotel = result.hotel
    else
      raise ActionController::RoutingError.new('Hotel not Found')
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/bookings/new.html.slim
.row
  .col-md-6.offset-md-3
    | Booking form
    - if @errors
      - @errors.each do |attr, msg|
        .err= "#{attr} #{msg}"
    .form
      = form_for(@booking_form, url: hotel_bookings_path, remote: false) do |f|
        .form-group
          =f.label :started_at, class: 'booking-label'
          =f.date_select :started_at, class: 'form-control'
        .form-group
          =f.label :ended_at, class: 'booking-label'
          =f.date_select :ended_at, class: 'form-control'
        .form-group
          =f.label :user_email, class: 'booking-label'
          =f.email_field :user_email, class: 'form-control'
        .form-group
          =f.label :user_name, class: 'booking-label'
          =f.text_field :user_name, class: 'form-control'
        .form-group
          =f.hidden_field :hotel_id
        .form-group
          =f.submit

app/views/home/index.html.slim
h1 Choose hotel and make book!

#map

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FindHotel
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .container
      = yield
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDcp1tHCiK3Bv8k6yjwdzTXE2SLINJnxbQ&libraries=places&callback=initMap'